language: perl
perl:
  - "5.8.1"
  - "5.8.5"
  - "5.8.8"
  - "5.8.9"
  - "5.10.0"
  - "5.10.1"
  - "5.12.0"
  - "5.12.5"
  - "5.18.2"
addons:
  apt:
    packages:
      - bash
      - dash
      - ksh
      - zsh
      - tcsh
      - csh
      - fish
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl
  - build-dist
  - cd $BUILD_DIR
  - local-lib
install:
  - cpan-install ExtUtils::MakeMaker~6.58 App::Prove --deps
after_install:
  - make realclean
script:
  - prove -lv $(test-dirs)
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
