language: perl
perl:
  - "5.8.1"
  - "5.8.5"
  - "5.8.8"
  - "5.8.9"
  - "5.10.0"
  - "5.10.1"
  - "5.12.0"
  - "5.12.5"
  - "5.18.2"
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - LL_ROOT="$(mktemp -d -t local-lib-XXXXXX)"
  - export PERL5LIB="$LL_ROOT/lib/perl5"
  - export PERL_CPANM_OPT="-l $LL_ROOT"
  - cpan-install ExtUtils::MakeMaker~6.58 --deps
script:
  - "prove -lv $(test-dirs) :: -f"
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
